version: 1.0.{build}
before_build:
  - cmd: pip install -U pip
  - cmd: pip install pytest codecov
build_script:
  - cmd: pip install -e .[test]
test_script:
  - cmd: coverage run --source=yamlconfig -m pytest -v
on_success:
  - cmd: codecov
